/**
 * 把 codex 主题配置文件（VS Code 风格 colors/tokenColors 清单）
 * 转换为插件的主题预设表 src/client/presets.ts。
 *
 * 用法：
 *   node scripts/build-presets.mjs [path/to/codex-themes.json]
 *   缺省读环境变量 $CODEX_THEMES_JSON，都没有则报错
 *
 * 映射规则（每个主题 → 一组 Codex 参数）：
 * - surface    = editor.background
 * - ink        = editor.foreground → foreground
 * - accent     = focusBorder → textLink.foreground → button.background
 *                → activityBarBadge.background
 * - sidebar    = sideBar.background → activityBar.background（空 = 派生）
 * - contrast   = 45（浅色）/ 60（深色）固定
 * - diff/skill = Codex 默认值（原文件 tokenColors 不含 diff 色）
 * 8 位 hex 去掉 alpha；非法值回落默认。
 */
import { readFileSync, writeFileSync } from "node:fs";
import { basename, resolve } from "node:path";

const SOURCE = process.argv[2] ?? process.env.CODEX_THEMES_JSON;
if (SOURCE === undefined) {
  throw new Error(
    "missing source: pass a path argument or set CODEX_THEMES_JSON (e.g. node scripts/build-presets.mjs path/to/codex-themes.json)",
  );
}

/** 规范化 #RRGGBB（8 位 hex 截掉 alpha；非法返回空串）。 */
function normalizeHex(value) {
  if (typeof value !== "string") return "";
  const match = /^#([0-9a-fA-F]{6})(?:[0-9a-fA-F]{2})?$/.exec(value.trim());
  return match ? `#${match[1].toUpperCase()}` : "";
}

const DEFAULT_KNOBS = {
  light: { accent: "#339CFF", surface: "#FFFFFF", ink: "#1A1C1F", contrast: 45, diffAdded: "#00A240", diffRemoved: "#BA2623", skill: "#924FF7" },
  dark: { accent: "#0169CC", surface: "#111111", ink: "#FCFCFC", contrast: 60, diffAdded: "#00A240", diffRemoved: "#E02E2A", skill: "#B06DFF" },
};

/** 相对亮度（WCAG）。 */
function luminance(hex) {
  const channels = [1, 3, 5].map((start) => Number.parseInt(hex.slice(start, start + 2), 16) / 255);
  const linear = channels.map((c) => (c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4)));
  return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2];
}

/** WCAG 对比度。 */
function contrast(a, b) {
  const la = luminance(a);
  const lb = luminance(b);
  const [hi, lo] = la >= lb ? [la, lb] : [lb, la];
  return (hi + 0.05) / (lo + 0.05);
}

function toKnobs(theme, mode) {
  const colors = theme.colors ?? {};
  const fallback = DEFAULT_KNOBS[mode];
  const surface = normalizeHex(colors["editor.background"]) || fallback.surface;
  /** 强调色候选按与背景的对比度择优（避免米白/浅灰等隐身强调色）。 */
  const accentCandidates = [
    colors.focusBorder,
    colors["textLink.foreground"],
    colors["button.background"],
    colors["activityBarBadge.background"],
  ];
  let best = "";
  let bestScore = -1;
  for (const candidate of accentCandidates) {
    const value = normalizeHex(candidate);
    if (value === "") continue;
    const score = contrast(value, surface);
    if (score > bestScore) {
      best = value;
      bestScore = score;
    }
  }
  const accent = bestScore < 1.8 ? fallback.accent : best;
  const sidebar =
    normalizeHex(colors["sideBar.background"]) || normalizeHex(colors["activityBar.background"]);
  return {
    accent,
    surface,
    ink:
      normalizeHex(colors["editor.foreground"]) ||
      normalizeHex(colors.foreground) ||
      fallback.ink,
    contrast: fallback.contrast,
    diffAdded: fallback.diffAdded,
    diffRemoved: fallback.diffRemoved,
    skill: fallback.skill,
    sidebar,
  };
}

const data = JSON.parse(readFileSync(SOURCE, "utf8"));
if (!Array.isArray(data)) throw new Error("codex-themes.json must be a top-level array");

const light = [];
const dark = [];
for (const theme of data) {
  const type = theme.type === "light" ? "light" : "dark";
  const preset = { name: theme.name, knobs: toKnobs(theme, type) };
  (type === "light" ? light : dark).push(preset);
}

const lines = [];
lines.push(`/**`);
lines.push(` * @generated by scripts/build-presets.mjs — 不要手改。`);
lines.push(` * 来源：${basename(SOURCE)}`);
lines.push(` * 浅色 ${light.length} 款 + 深色 ${dark.length} 款（index 0 = Codex 默认）。`);
lines.push(` */`);
lines.push(`import type { ModeKnobs } from "../defaults.js";`);
lines.push(``);
lines.push(`export interface ThemePreset {`);
lines.push(`  readonly name: string;`);
lines.push(`  readonly knobs: ModeKnobs;`);
lines.push(`}`);
lines.push(``);
for (const [list, label] of [[light, "LIGHT_PRESETS"], [dark, "DARK_PRESETS"]]) {
  lines.push(`export const ${label}: readonly ThemePreset[] = [`);
  const defaults = DEFAULT_KNOBS[label === "LIGHT_PRESETS" ? "light" : "dark"];
  lines.push(`  { name: "Codex 默认", knobs: { accent: "${defaults.accent}", surface: "${defaults.surface}", ink: "${defaults.ink}", contrast: ${defaults.contrast}, diffAdded: "${defaults.diffAdded}", diffRemoved: "${defaults.diffRemoved}", skill: "${defaults.skill}", sidebar: "" } },`);
  for (const preset of list) {
    const k = preset.knobs;
    lines.push(
      `  { name: ${JSON.stringify(preset.name)}, knobs: { accent: "${k.accent}", surface: "${k.surface}", ink: "${k.ink}", contrast: ${k.contrast}, diffAdded: "${k.diffAdded}", diffRemoved: "${k.diffRemoved}", skill: "${k.skill}", sidebar: "${k.sidebar}" } },`,
    );
  }
  lines.push(`];`);
  lines.push(``);
}

const target = resolve("src/client/presets.ts");
writeFileSync(target, lines.join("\n"));
console.log(`generated ${target}: light=${light.length} dark=${dark.length}`);
